[package]
name = "khata"
version = "0.0.2"
authors = ["Kushal Das <mail@kushaldas.in>"]
description = "Static blogging tool, Shonku reimplemented."
license = "GPL-3.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.1.6"
tera = "0.11"
clap = "2.33.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
pulldown-cmark = "0.5.3"
sha2 = "0.8.0"
hex = "0.3.2"
rss = "1.8.0"

[dependencies.chrono]
version = "0.4"
features = ["rustc-serialize"]

