[package]
name = "khata"
version = "0.0.1"
authors = ["Kushal Das <mail@kushaldas.in>"]
description = "Static blogging tool, Shonku reimplemented."
license = "GPLv3+"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.1.6"
chrono = "0.4"
tera = "0.11"